steps:
  - label: "fossa analyze"
    agents:
      queue: "init"
      docker: "*"
    command: "./scripts/buildkite/fossa.sh"
  - label: "proto lint"
    agents:
      queue: "workers"
      docker: "*"
    command: "make proto-lint"
