steps:
  - label: "fossa analyze"
    agents:
      queue: "buildkite-gcp-large"
    command: "./scripts/buildkite/fossa.sh"
  - label: "proto lint"
    agents:
      queue: "buildkite-gcp-large"
    command: "make proto-lint"
